// Tests for the ported island spec core (U1). Ports the island-editor suites
// for the same modules (parity through shared vectors, not re-derivation) and
// adds the engine-only pieces: golden parity against the editor implementation
// (fixture regenerated by `pnpm sync:island`), the fallback-path validator
// divergence (v1/v2 rejected), and the hydrate-time snap helper.

import { describe, expect, it } from 'vitest'
import committedSpecJson from '~/engine/student-space/Game/Data/defaultIslandSpec.json'
import {
  BLADES_PER_CELL,
  grassBlades,
} from '~/engine/student-space/Game/State/islandSpecCore/grassField.ts'
import {
  decodeGrid,
  encodeGrid,
  type SerializedGrid,
} from '~/engine/student-space/Game/State/islandSpecCore/gridCodec.ts'
import { shoreDistanceField } from '~/engine/student-space/Game/State/islandSpecCore/shoreField.ts'
import {
  claimCellAt,
  occupiedCellsFromSpec,
  type SnapEnv,
  snapPositionToLand,
} from '~/engine/student-space/Game/State/islandSpecCore/snapToLand.ts'
import {
  deserializeSpec,
  serializeSpec,
  validateSpecObject,
} from '~/engine/student-space/Game/State/islandSpecCore/specIO.ts'
import {
  blurTiers,
  cellCenter,
  cellIndex,
  createOceanGrid,
  DEFAULT_TIER_HEIGHTS,
  evaluateHeight,
  GRID_COLS,
  GRID_ROWS,
  type IslandSpec,
  LEGACY_DEFAULT_TIER_HEIGHTS,
  MAX_TIER,
  SURFACE_AUTO,
  SURFACE_GRASS,
  type TerrainGrid,
  terraceHeight,
  worldPositionOfObject,
  worldToCell,
} from '~/engine/student-space/Game/State/islandSpecCore/terrainGrid.ts'
import golden from './fixtures/islandSpecGolden.json'

const WORLD = 24

function specFrom(grid: TerrainGrid): IslandSpec {
  return {
    version: 5,
    worldSize: WORLD,
    seaLevel: 0,
    tierHeights: DEFAULT_TIER_HEIGHTS,
    grid,
    objects: [],
  }
}

function uniformGrid(tier: number): TerrainGrid {
  const grid = createOceanGrid()
  grid.tiers.fill(tier)
  return grid
}

/** Stamp a `size`×`size` block of `tier` centered on cell (32,32), anchored so
 *  (32,32) is always included (half = floor(size/2), matching the plan-032
 *  invariant probe). size=1 stamps only (32,32); size=2 stamps the 2×2 block
 *  with (32,32) at its lower-right corner; size=5 stamps a true 5×5 square
 *  centered on (32,32). */
function stampSquare(tier: number, size: number): TerrainGrid {
  const grid = createOceanGrid()
  const half = Math.floor(size / 2)
  for (let dr = -half; dr <= size - 1 - half; dr++) {
    for (let dc = -half; dc <= size - 1 - half; dc++) {
      grid.tiers[(32 + dr) * GRID_COLS + (32 + dc)] = tier
    }
  }
  return grid
}

const committedSpec = validateSpecObject(committedSpecJson)

// ── Golden parity with the editor implementation (KTD-2) ─────────────────────

describe('golden parity — committed spec vs editor implementation', () => {
  it('evaluateHeight matches the editor at every golden lattice point', () => {
    const blurred = blurTiers(committedSpec.grid)
    for (const { x, z, h } of golden.heights) {
      expect(evaluateHeight(committedSpec, x, z, blurred)).toBeCloseTo(h, 10)
    }
  })

  it('worldPositionOfObject matches the editor for every committed object', () => {
    const blurred = blurTiers(committedSpec.grid)
    const byId = new Map(committedSpec.objects.map((o) => [o.id, o]))
    expect(byId.size).toBe(golden.objects.length)
    for (const g of golden.objects) {
      const o = byId.get(g.id)
      expect(o, `object ${g.id} missing from committed spec`).toBeDefined()
      if (!o) continue
      expect(o.kind).toBe(g.kind)
      const p = worldPositionOfObject(committedSpec, o, blurred)
      expect(p.x).toBeCloseTo(g.x, 10)
      expect(p.y).toBeCloseTo(g.y, 10)
      expect(p.z).toBeCloseTo(g.z, 10)
    }
  })

  it('the character spawn (cell 40,66) lands at ≈ (−4.41, y, 0.47) — coordinate convention anchor', () => {
    // plan 031: island resampled 64×64 → 128×128 — the character's cell
    // remapped (20,33) → (40,66), shifting the cell-center world position by
    // −cellSize/2 = −0.09375 per axis (cellSize 24/128 = 0.1875).
    const character = committedSpec.objects.find((o) => o.kind === 'character')
    expect(character).toBeDefined()
    if (!character) return
    expect(character.c).toBe(40)
    expect(character.r).toBe(66)
    const p = worldPositionOfObject(committedSpec, character)
    expect(p.x).toBeCloseTo(-4.40625, 4)
    expect(p.z).toBeCloseTo(0.46875, 4)
  })

  it('grass scatter matches the editor: count and the first blades', () => {
    const blades = grassBlades(committedSpec)
    expect(blades.length).toBe(golden.grass.count)
    for (let i = 0; i < golden.grass.first.length; i++) {
      const g = golden.grass.first[i]
      const b = blades[i]
      expect(b).toBeDefined()
      if (!b || !g) continue
      expect(b.x).toBeCloseTo(g.x, 10)
      expect(b.y).toBeCloseTo(g.y, 10)
      expect(b.z).toBeCloseTo(g.z, 10)
      expect(b.yaw).toBeCloseTo(g.yaw, 10)
      expect(b.height).toBeCloseTo(g.height, 10)
      expect(b.shade).toBeCloseTo(g.shade, 10)
      expect(b.phase).toBeCloseTo(g.phase, 10)
    }
  })
})

// ── terrainGrid (ported editor suite) ────────────────────────────────────────

describe('terrainGrid — terrace evaluation', () => {
  it('a flat uniform grid evaluates to exactly its tier top at an interior cell center', () => {
    for (const tier of [1, 2, 3]) {
      const spec = specFrom(uniformGrid(tier))
      const { x, z } = cellCenter(WORLD, spec.grid, 32, 32)
      expect(evaluateHeight(spec, x, z)).toBeCloseTo(DEFAULT_TIER_HEIGHTS[tier] ?? Number.NaN, 10)
    }
  })

  it('plan 032 feature-preservation floor: a lone cell sinks, a 2×2 block stays visible land, a 5×5 block is a raised bump', () => {
    // At BLUR_PASSES = 4 / BLUR_MIX = 0.85 (plan 032, retuned for the 128×128
    // grid's coastline curves — plan 031), the old "isolated single cell stays
    // a raised bump" floor no longer holds, and that's DELIBERATE: the
    // maintainer's island art direction is "few big smooth scalloped masses" —
    // sub-2×2 detail is intentionally not authorable at this blur strength.
    // The redefined, verified floor:
    //   - a lone tier-2 cell samples ≈0.427 → terraces to ≈−0.943, BELOW sea
    //     level (sinks; asserted as expected, not a regression).
    //   - a 2×2 tier-2 block (≈ the old single 64-grid cell's world footprint,
    //     0.375 units) samples ≈0.712 → terraces to exactly tierHeights[1]
    //     (0.05) — the preserved "stays visible land" floor.
    //   - a 5×5 tier-2 block (~0.94 world units) samples ≈1.769 → terraces to
    //     tierHeights[2] (1.0) — a full raised bump, the new practical minimum
    //     for a plateau-height feature.

    // (a) lone cell — intentionally sinks below sea level.
    {
      const grid = stampSquare(2, 1)
      const spec = specFrom(grid)
      const blurred = blurTiers(grid)
      const center = cellCenter(WORLD, grid, 32, 32)
      const h = evaluateHeight(spec, center.x, center.z, blurred)
      expect(h).toBeLessThan(spec.seaLevel)
      expect(h).toBeCloseTo(-0.9429203040213103, 6) // observed; plan 032
    }

    // (b) 2×2 block — preserved "visible land" floor.
    {
      const grid = stampSquare(2, 2)
      const spec = specFrom(grid)
      const blurred = blurTiers(grid)
      const center = cellCenter(WORLD, grid, 32, 32)
      const h = evaluateHeight(spec, center.x, center.z, blurred)
      expect(h).toBeGreaterThanOrEqual(DEFAULT_TIER_HEIGHTS[1] ?? Number.NaN)
      expect(h).toBeCloseTo(0.05, 6) // observed; plan 032 — exactly tierHeights[1]
    }

    // (c) 5×5 block — a raised bump, the new practical minimum.
    {
      const grid = stampSquare(2, 5)
      const spec = specFrom(grid)
      const blurred = blurTiers(grid)
      const center = cellCenter(WORLD, grid, 32, 32)
      const h = evaluateHeight(spec, center.x, center.z, blurred)
      expect(h).toBeGreaterThan(DEFAULT_TIER_HEIGHTS[1] ?? Number.NaN)
      expect(h).toBeCloseTo(1, 6) // observed; plan 032 — exactly tierHeights[2]
    }
  })

  it('terraceHeight at an integer tier returns exactly that tier top', () => {
    for (let t = 0; t <= MAX_TIER; t++) {
      expect(terraceHeight(t, DEFAULT_TIER_HEIGHTS)).toBeCloseTo(
        DEFAULT_TIER_HEIGHTS[t] ?? Number.NaN,
        10,
      )
    }
  })

  it('blur treats out-of-bounds as ocean: a corner is lower than the interior on a uniform grid', () => {
    const grid = uniformGrid(1)
    const blurred = blurTiers(grid)
    const corner = blurred[0] ?? Number.NaN
    const interior = blurred[32 * GRID_COLS + 32] ?? Number.NaN
    expect(interior).toBeCloseTo(1, 6)
    expect(corner).toBeLessThan(interior)
  })

  it('worldToCell and cellCenter round-trip', () => {
    const grid = createOceanGrid()
    for (const [c, r] of [
      [0, 0],
      [32, 17],
      [63, 63],
      [10, 50],
    ] as const) {
      const { x, z } = cellCenter(WORLD, grid, c, r)
      const back = worldToCell(WORLD, grid, x, z)
      expect(back).toEqual({ c, r })
    }
  })

  it('createOceanGrid is all ocean with matching dimensions', () => {
    const grid = createOceanGrid()
    expect(grid.cols).toBe(GRID_COLS)
    expect(grid.rows).toBe(GRID_ROWS)
    expect(grid.tiers).toHaveLength(GRID_COLS * GRID_ROWS)
    expect(grid.tiers.every((t) => t === 0)).toBe(true)
    expect(grid.surface.every((s) => s === 0)).toBe(true)
  })
})

// ── gridCodec (ported editor suite) ──────────────────────────────────────────

function sampleGrid() {
  const grid = createOceanGrid(4, 3)
  grid.tiers[0] = 4
  grid.tiers[5] = 2
  grid.surface[5] = SURFACE_GRASS
  return grid
}

function encoded(): SerializedGrid {
  return encodeGrid(sampleGrid())
}

describe('gridCodec', () => {
  it('round-trips a grid through encode/decode', () => {
    const grid = sampleGrid()
    expect(decodeGrid(encodeGrid(grid))).toEqual(grid)
  })

  it('encodes rows as digit strings of the right shape', () => {
    const s = encodeGrid(createOceanGrid(4, 3))
    expect(s.cols).toBe(4)
    expect(s.rows).toBe(3)
    expect(s.tiers).toEqual(['0000', '0000', '0000'])
    expect(s.surface).toEqual(['0000', '0000', '0000'])
  })

  it('throws on wrong row count', () => {
    const s = encoded()
    s.tiers = s.tiers.slice(0, 2)
    expect(() => decodeGrid(s)).toThrow(/must have 3 rows/)
  })

  it('throws on wrong row length', () => {
    const s = encoded()
    s.tiers[1] = '00000'
    expect(() => decodeGrid(s)).toThrow(/must be 4 chars/)
  })

  it('throws on non-digit chars', () => {
    const s = encoded()
    s.tiers[0] = 'x000'
    expect(() => decodeGrid(s)).toThrow(/not a digit/)
  })

  it('throws when a tier digit exceeds MAX_TIER', () => {
    const s = encoded()
    s.tiers[0] = `${String(MAX_TIER + 1)}000`
    expect(() => decodeGrid(s)).toThrow(/exceeds max/)
  })

  it('throws when a surface digit exceeds SURFACE_GRASS', () => {
    const s = encoded()
    s.surface[0] = '2000'
    expect(() => decodeGrid(s)).toThrow(/exceeds max/)
  })

  it('throws on missing cols/rows', () => {
    expect(() => decodeGrid({ tiers: [], surface: [] })).toThrow(/cols must be a positive integer/)
  })
})

// ── specIO (ported editor suite, minus the unported v1/v2 rasterizer) ────────

describe('specIO', () => {
  it('round-trips the committed v5 spec through serialize/deserialize', () => {
    const back = deserializeSpec(serializeSpec(committedSpec))
    expect(back).toEqual(committedSpec)
  })

  it('accepts the committed v5 save', () => {
    const spec = validateSpecObject(committedSpecJson)
    expect(spec.version).toBe(5)
    expect(spec.worldSize).toBe(24)
    expect(spec.objects.length).toBeGreaterThan(0)
  })

  it('REJECTS v1/v2 payloads (deliberate divergence: fallback path, no legacy rasterizer)', () => {
    const v2 = {
      version: 2,
      worldSize: 24,
      coastline: [
        { x: 6, z: 0 },
        { x: -6, z: 5 },
        { x: -6, z: -5 },
      ],
      heightProfile: {
        seaLevel: 0.25,
        plateauHeight: 1,
        coastFalloff: 2,
        cliffSteepness: 0.45,
        seafloorDepth: -1.2,
      },
      relief: { resolution: 4, data: new Array(16).fill(0) },
    }
    expect(() => validateSpecObject(v2)).toThrow(/version must be/)
    expect(() => validateSpecObject({ ...v2, version: 1 })).toThrow(/version must be/)
  })

  it('migrates a v3 spec to v5 with an empty objects array', () => {
    const parsed = JSON.parse(serializeSpec(committedSpec))
    parsed.version = 3
    parsed.objects = undefined
    const spec = validateSpecObject(parsed)
    expect(spec.version).toBe(5)
    expect(spec.objects).toEqual([])
  })

  it('throws on an unsupported version', () => {
    const parsed = JSON.parse(serializeSpec(committedSpec))
    parsed.version = 6
    expect(() => validateSpecObject(parsed)).toThrow(/version must be/)
  })

  it('throws on an invalid object entry (unknown kind)', () => {
    const parsed = JSON.parse(serializeSpec(committedSpec))
    parsed.objects = [{ id: 'x', kind: 'dragon', c: 0, r: 0, yaw: 0, scale: 1 }]
    expect(() => validateSpecObject(parsed)).toThrow(/objects\[0\]\.kind/)
  })

  it('migrates the retired tree kinds (fruitTree/pine/palm) to `tree` instead of rejecting the spec', () => {
    const parsed = JSON.parse(serializeSpec(committedSpec))
    parsed.objects = [
      { id: 'a', kind: 'fruitTree', c: 1, r: 1, yaw: 0, scale: 1 },
      { id: 'b', kind: 'pine', c: 2, r: 2, yaw: 0, scale: 1 },
      { id: 'c', kind: 'palm', c: 3, r: 3, yaw: 0, scale: 1 },
      { id: 'd', kind: 'rock', c: 4, r: 4, yaw: 0, scale: 1 },
    ]
    const spec = validateSpecObject(parsed)
    expect(spec.objects.map((o) => o.kind)).toEqual(['tree', 'tree', 'tree', 'rock'])
    expect(spec.objects.map((o) => o.id)).toEqual(['a', 'b', 'c', 'd'])
  })

  it('throws on an object with an out-of-range cell', () => {
    const parsed = JSON.parse(serializeSpec(committedSpec))
    parsed.objects = [{ id: 'x', kind: 'rock', c: 9999, r: 0, yaw: 0, scale: 1 }]
    expect(() => validateSpecObject(parsed)).toThrow(/objects\[0\]\.c/)
  })

  it('throws on an object with a non-positive scale', () => {
    const parsed = JSON.parse(serializeSpec(committedSpec))
    parsed.objects = [{ id: 'x', kind: 'rock', c: 0, r: 0, yaw: 0, scale: 0 }]
    expect(() => validateSpecObject(parsed)).toThrow(/objects\[0\]\.scale/)
  })

  it('normalizes two character entries down to the FIRST, everything else preserved', () => {
    const parsed = JSON.parse(serializeSpec(committedSpec))
    parsed.objects = [
      { id: 'rock-1', kind: 'rock', c: 0, r: 0, yaw: 0, scale: 1 },
      { id: 'char-first', kind: 'character', c: 10, r: 10, yaw: 0, scale: 1 },
      { id: 'char-second', kind: 'character', c: 20, r: 20, yaw: 0, scale: 1 },
      { id: 'tree-1', kind: 'tree', c: 5, r: 5, yaw: 0, scale: 1 },
    ]
    const spec = validateSpecObject(parsed)
    expect(spec.objects.map((o) => o.id)).toEqual(['rock-1', 'char-first', 'tree-1'])
    expect(spec.objects.filter((o) => o.kind === 'character')).toHaveLength(1)
  })

  it('throws on malformed JSON', () => {
    expect(() => deserializeSpec('{not json')).toThrow(/malformed JSON/)
  })

  it('throws when tierHeights is not strictly ascending', () => {
    const bad = JSON.parse(serializeSpec(committedSpec))
    bad.tierHeights = [0, 0, 1, 2, 3]
    expect(() => validateSpecObject(bad)).toThrow(/strictly-ascending/)
  })

  it('clears a v4 payload’s painted surface on load, preserving tiers and objects', () => {
    const grid = createOceanGrid()
    grid.surface[0] = SURFACE_GRASS
    grid.surface[10] = SURFACE_GRASS
    grid.tiers[0] = 2
    const parsed = {
      version: 4,
      worldSize: 24,
      seaLevel: 0,
      tierHeights: DEFAULT_TIER_HEIGHTS.slice(),
      grid,
      objects: [{ id: 'x', kind: 'rock', c: 5, r: 5, yaw: 0, scale: 1 }],
    }
    const spec = validateSpecObject(parsed)
    expect(spec.version).toBe(5)
    expect(spec.grid.surface.every((s) => s === SURFACE_AUTO)).toBe(true)
    expect(spec.grid.tiers[0]).toBe(2) // tiers untouched
    expect(spec.objects).toHaveLength(1)
  })

  it('preserves a v5 payload’s painted surface (grass survives its own round-trip)', () => {
    const grid = createOceanGrid()
    grid.surface[0] = SURFACE_GRASS
    grid.tiers[0] = 2
    const spec = validateSpecObject({
      version: 5,
      worldSize: 24,
      seaLevel: 0,
      tierHeights: DEFAULT_TIER_HEIGHTS.slice(),
      grid,
      objects: [],
    })
    expect(spec.grid.surface[0]).toBe(SURFACE_GRASS)
  })

  it('migrates a spec carrying exactly the legacy default tier heights to the current defaults', () => {
    const spec = validateSpecObject({
      version: 4,
      worldSize: 24,
      seaLevel: 0,
      tierHeights: LEGACY_DEFAULT_TIER_HEIGHTS.slice(),
      grid: createOceanGrid(),
      objects: [],
    })
    expect(spec.tierHeights).toEqual(DEFAULT_TIER_HEIGHTS)
  })

  it('preserves custom-authored tier heights untouched', () => {
    const custom = [-1, 0.3, 0.9, 1.4, 2]
    const spec = validateSpecObject({
      version: 4,
      worldSize: 24,
      seaLevel: 0,
      tierHeights: custom,
      grid: createOceanGrid(),
      objects: [],
    })
    expect(spec.tierHeights).toEqual(custom)
  })
})

// ── shoreField (ported editor suite) ─────────────────────────────────────────

function latticeAt(res: number, worldSize: number, x: number, z: number): number {
  const step = worldSize / res
  const half = worldSize / 2
  const i = Math.round((x + half) / step - 0.5)
  const j = Math.round((z + half) / step - 0.5)
  return j * res + i
}

describe('shoreDistanceField', () => {
  it('lattice resolution is scale × the grid resolution', () => {
    const grid = createOceanGrid()
    expect(shoreDistanceField(grid, WORLD, 2).res).toBe(GRID_COLS * 2)
    expect(shoreDistanceField(grid, WORLD, 3).res).toBe(GRID_COLS * 3)
  })

  it('a single land cell in ocean is negative at its center, positive around it, increasing outward', () => {
    const grid = createOceanGrid()
    grid.tiers[32 * GRID_COLS + 32] = 4
    const f = shoreDistanceField(grid, WORLD, 2)
    const step = WORLD / f.res
    const cx = -WORLD / 2 + (32 + 0.5) * (WORLD / GRID_COLS)
    const center = f.data[latticeAt(f.res, WORLD, cx, cx)] ?? Number.NaN
    expect(center).toBeLessThan(0) // land

    const ring1 = f.data[latticeAt(f.res, WORLD, cx + 2 * step, cx)] ?? Number.NaN
    const ring2 = f.data[latticeAt(f.res, WORLD, cx + 3 * step, cx)] ?? Number.NaN
    expect(ring1).toBeGreaterThan(0)
    expect(ring2).toBeGreaterThan(ring1)
    expect(ring2 - ring1).toBeGreaterThan(step * 0.5)
    expect(ring2 - ring1).toBeLessThan(step * 1.5)
  })

  it('an all-ocean grid is uniformly large positive', () => {
    const f = shoreDistanceField(createOceanGrid(), WORLD, 2)
    expect(f.data.every((v) => v > 0)).toBe(true)
    expect(f.data[0]).toBeGreaterThanOrEqual(WORLD)
  })

  it('a carved pond inside land is positive (water) at the pond center', () => {
    // plan 032: the feature-preservation floor is SYMMETRIC — shoreField reads
    // the same sampleTierField as the terrain mesh, so a carved water pocket
    // below ~5×5 cells (~0.9 world units) dissolves back into land exactly
    // like an isolated raised cell dissolves into the sea (see the
    // sampleTierField comment in terrainGrid.ts). A 3×3 pond (the pre-032
    // size) now samples as land (-24, deeply interior); 7×7 is the smallest
    // size this test pins as robustly water (observed center distance
    // ≈0.268, comfortably positive — 5×5 crosses to positive too, but only by
    // ≈0.047, too thin a margin to pin reliably).
    const grid = createOceanGrid()
    grid.tiers.fill(3)
    for (let r = 29; r <= 35; r++) {
      for (let c = 29; c <= 35; c++) grid.tiers[r * GRID_COLS + c] = 0
    }
    const f = shoreDistanceField(grid, WORLD, 2)
    const cx = -WORLD / 2 + (32 + 0.5) * (WORLD / GRID_COLS)
    expect(f.data[latticeAt(f.res, WORLD, cx, cx)]).toBeGreaterThan(0)
  })

  it('the sign flips exactly at the boundary (no zero-valued lattice points)', () => {
    const grid = createOceanGrid()
    for (let r = 20; r < 44; r++) {
      for (let c = 20; c < 44; c++) grid.tiers[r * GRID_COLS + c] = 3
    }
    const f = shoreDistanceField(grid, WORLD, 2)
    let flips = 0
    for (let idx = 0; idx < f.data.length - 1; idx++) {
      if (idx % f.res === f.res - 1) continue // skip row wrap
      expect(f.data[idx]).not.toBe(0)
      if (Math.sign(f.data[idx] ?? 0) !== Math.sign(f.data[idx + 1] ?? 0)) flips++
    }
    expect(flips).toBeGreaterThan(0)
  })
})

// ── grassField (ported editor suite) ─────────────────────────────────────────

describe('grassField — grassBlades', () => {
  it('emits nothing for an unpainted (all-auto) grid', () => {
    expect(grassBlades(specFrom(createOceanGrid()))).toEqual([])
  })

  it('scatters exactly BLADES_PER_CELL blades near an interior painted land cell', () => {
    const grid = createOceanGrid()
    const c = 32
    const r = 32
    // Raise the whole 3×3 neighborhood so the blurred terrain stays above sea
    // level across the painted cell's full scatter radius.
    for (let dr = -1; dr <= 1; dr++) {
      for (let dc = -1; dc <= 1; dc++) {
        grid.tiers[cellIndex(grid, c + dc, r + dr)] = 2
      }
    }
    grid.surface[cellIndex(grid, c, r)] = SURFACE_GRASS
    const spec = specFrom(grid)
    const blades = grassBlades(spec)
    expect(blades).toHaveLength(BLADES_PER_CELL)

    const cellSize = WORLD / grid.cols
    const center = cellCenter(WORLD, grid, c, r)
    for (const b of blades) {
      expect(Math.abs(b.x - center.x)).toBeLessThanOrEqual(0.575 * cellSize)
      expect(Math.abs(b.z - center.z)).toBeLessThanOrEqual(0.575 * cellSize)
    }
  })

  it('clips blades that spill onto a terrace wall', () => {
    // plan 032: the wider 4-pass blur reaches ~4 cells, so a 3×3 plateau (the
    // pre-032 size) no longer produces a representative wall within the
    // blade's ±0.575-cell jitter radius — every blade stayed on the plateau
    // (observed 16/16, no clipping). Enlarged to a 5×5 plateau (same tiers:
    // wall one column east, plateau elsewhere) so the wall is far enough from
    // the ocean-diluted interior to read as a real cliff again (observed
    // 9/16 survive — some spill onto the wall and get clipped, as intended).
    const grid = createOceanGrid()
    const c = 32
    const r = 32
    for (let dr = -2; dr <= 2; dr++) {
      for (let dc = -2; dc <= 2; dc++) {
        grid.tiers[cellIndex(grid, c + dc, r + dr)] = dc === 2 ? 1 : 2
      }
    }
    grid.surface[cellIndex(grid, c, r)] = SURFACE_GRASS
    const spec = specFrom(grid)
    const blades = grassBlades(spec)

    expect(blades.length).toBeGreaterThan(0)
    expect(blades.length).toBeLessThan(BLADES_PER_CELL)

    const center = cellCenter(WORLD, grid, c, r)
    const yCell = evaluateHeight(spec, center.x, center.z)
    for (const b of blades) {
      expect(Math.abs(b.y - yCell)).toBeLessThanOrEqual(0.05)
    }
  })

  it('emits nothing for a grass-painted WATER cell', () => {
    const grid = createOceanGrid()
    grid.surface[cellIndex(grid, 10, 10)] = SURFACE_GRASS
    expect(grassBlades(specFrom(grid))).toHaveLength(0)
  })

  it('is deterministic: two calls on the same spec produce identical output', () => {
    const grid = createOceanGrid()
    for (const [c, r] of [
      [10, 10],
      [20, 30],
      [40, 15],
    ] as const) {
      grid.tiers[cellIndex(grid, c, r)] = 2
      grid.surface[cellIndex(grid, c, r)] = SURFACE_GRASS
    }
    const spec = specFrom(grid)
    expect(grassBlades(spec)).toEqual(grassBlades(spec))
  })

  it("every blade's y is the terrain height at the blade's own x/z, above sea level", () => {
    const grid = createOceanGrid()
    for (let dr = -1; dr <= 1; dr++) {
      for (let dc = -1; dc <= 1; dc++) {
        grid.tiers[cellIndex(grid, 32 + dc, 32 + dr)] = 3
      }
    }
    grid.surface[cellIndex(grid, 32, 32)] = SURFACE_GRASS
    const spec = specFrom(grid)
    const blades = grassBlades(spec)
    expect(blades.length).toBeGreaterThan(0)
    for (const b of blades.slice(0, 5)) {
      expect(b.y).toBeCloseTo(evaluateHeight(spec, b.x, b.z), 10)
    }
    for (const b of blades) {
      expect(b.y).toBeGreaterThan(spec.seaLevel)
    }
  })

  it('respects a custom perCell density', () => {
    const grid = createOceanGrid()
    for (let dr = -1; dr <= 1; dr++) {
      for (let dc = -1; dc <= 1; dc++) {
        grid.tiers[cellIndex(grid, 32 + dc, 32 + dr)] = 2
      }
    }
    grid.surface[cellIndex(grid, 32, 32)] = SURFACE_GRASS
    expect(grassBlades(specFrom(grid), 3)).toHaveLength(3)
  })
})

// ── snapToLand (engine-only, KTD-7) ──────────────────────────────────────────

describe('snapToLand', () => {
  // A 12×12 world over an 8×8 grid; valid = inside the central 4×4 cell block.
  function makeEnv(): SnapEnv {
    const worldSize = 12
    const cols = 8
    const rows = 8
    return {
      worldSize,
      cols,
      rows,
      isValid: (x, z) => Math.abs(x) < 3 && Math.abs(z) < 3,
    }
  }

  it('returns a valid position untouched and claims nothing', () => {
    const env = makeEnv()
    const occupied = new Set<number>()
    expect(snapPositionToLand(env, occupied, 0.4, -1.2)).toEqual({ x: 0.4, z: -1.2 })
    expect(occupied.size).toBe(0)
  })

  it('snaps an invalid position to the nearest valid cell center and claims it', () => {
    const env = makeEnv()
    const occupied = new Set<number>()
    const snapped = snapPositionToLand(env, occupied, 5.5, 0.1)
    expect(snapped).not.toBeNull()
    if (!snapped) return
    expect(env.isValid(snapped.x, snapped.z)).toBe(true)
    expect(occupied.size).toBe(1)
  })

  it('clustered invalid positions land on distinct cells', () => {
    const env = makeEnv()
    const occupied = new Set<number>()
    const results = [
      snapPositionToLand(env, occupied, 5.5, 5.5),
      snapPositionToLand(env, occupied, 5.5, 5.5),
      snapPositionToLand(env, occupied, 5.5, 5.5),
    ]
    for (const p of results) expect(p).not.toBeNull()
    const keys = results.map((p) => (p ? `${p.x},${p.z}` : ''))
    expect(new Set(keys).size).toBe(3)
    expect(occupied.size).toBe(3)
  })

  it('never lands on a pre-occupied cell (spec decorative objects / character)', () => {
    const occupied = occupiedCellsFromSpec(committedSpec)
    const preSeeded = new Set(occupied)
    // committed spec has 17 objects — all their cells are pre-claimed
    expect(preSeeded.size).toBeGreaterThan(0)
    const snapped = snapPositionToLand(
      {
        worldSize: committedSpec.worldSize,
        cols: committedSpec.grid.cols,
        rows: committedSpec.grid.rows,
        // land = above sea level (coarse validity for the test)
        isValid: (x, z) => evaluateHeight(committedSpec, x, z) > committedSpec.seaLevel + 0.02,
      },
      occupied,
      -20,
      0.5, // far off-world, west of the island
    )
    expect(snapped).not.toBeNull()
    if (!snapped) return
    const { c, r } = worldToCell(committedSpec.worldSize, committedSpec.grid, snapped.x, snapped.z)
    expect(preSeeded.has(cellIndex(committedSpec.grid, c, r))).toBe(false)
  })

  it('claimCellAt reserves the cell of an already-valid object', () => {
    const env = makeEnv()
    const occupied = new Set<number>()
    claimCellAt(env, occupied, 0.4, -1.2)
    expect(occupied.size).toBe(1)
    // an invalid object snapping toward that cell skips it
    const snapped = snapPositionToLand(env, occupied, 0.4, -6)
    expect(snapped).not.toBeNull()
    if (!snapped) return
    expect(occupied.size).toBe(2)
  })

  it('returns null when no valid cell exists', () => {
    const env: SnapEnv = { worldSize: 12, cols: 8, rows: 8, isValid: () => false }
    expect(snapPositionToLand(env, new Set(), 1, 1)).toBeNull()
  })
})
