// pnpm sync:island — copy the island editor's saved spec into the engine and
// regenerate the golden parity fixture (KTD-2).
//
// 1. Validates `island-editor/saves/island.json` through the ENGINE's ported
//    validator — the sync gate and the boot loader can never disagree. Fails
//    non-zero on an invalid save.
// 2. Writes the normalized serialization to
//    `src/engine/student-space/Game/Data/defaultIslandSpec.json` and the frozen
//    fallback snapshot to `.../fallbackIslandSpec.ts` (one re-authoring keeps
//    both the committed spec and the fallback valid).
// 3. Regenerates `test/engine/fixtures/islandSpecGolden.json` from the EDITOR's
//    own terrain implementation (imported straight from the island-editor
//    workspace sources — the same code its tests run). Same-version semantic
//    drift in the editor's math therefore fails the engine golden test at the
//    next `pnpm test` instead of shipping silently: a failing golden test after
//    a sync means the ported math must be re-synced before the new spec lands.
//
// Run with: pnpm sync:island   (tsx, like every other root script)

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
// Engine (ported) validator — the boot loader's exact code path.
import {
  serializeSpec,
  validateSpecObject,
} from '../src/engine/student-space/Game/State/islandSpecCore/specIO.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

// Editor implementation — the golden fixture's source of truth. Pure TS with no
// deps; tsx compiles it straight from the island-editor workspace sources.
// Imported DYNAMICALLY with computed paths so the root `tsc` program (stricter
// than the editor's: noUncheckedIndexedAccess) never type-checks editor code —
// the editor's own gate (`pnpm check:island-editor`) owns that.
const editorModule = (rel: string) =>
  import(pathToFileURL(resolve(root, 'island-editor', rel)).href)
const { validateSpecObject: editorValidateSpecObject } = await editorModule('src/editor/specIO.ts')
const { grassBlades: editorGrassBlades } = await editorModule('src/terrain/grassField.ts')
const {
  blurTiers: editorBlurTiers,
  evaluateHeight: editorEvaluateHeight,
  worldPositionOfObject: editorWorldPositionOfObject,
} = await editorModule('src/terrain/terrainGrid.ts')
// Optional positional arg = alternate save path (used to verify the invalid-
// save non-zero exit without touching the real save).
const savePath = process.argv[2]
  ? resolve(process.cwd(), process.argv[2])
  : resolve(root, 'island-editor/saves/island.json')
const specJsonPath = resolve(root, 'src/engine/student-space/Game/Data/defaultIslandSpec.json')
const fallbackPath = resolve(root, 'src/engine/student-space/Game/Data/fallbackIslandSpec.ts')
const goldenPath = resolve(root, 'test/engine/fixtures/islandSpecGolden.json')

// ── 1. Validate the save through the ENGINE validator (the sync gate) ────────

let parsed: unknown
try {
  parsed = JSON.parse(readFileSync(savePath, 'utf8'))
} catch (error) {
  console.error(`[sync:island] cannot read/parse ${savePath}:`, error)
  process.exit(1)
}

let spec: ReturnType<typeof validateSpecObject>
try {
  spec = validateSpecObject(parsed)
} catch (error) {
  console.error('[sync:island] save rejected by the engine validator — not syncing:', error)
  process.exit(1)
}

// Cross-check against the editor's validator: both must normalize the save to
// the same spec, or the ported code has drifted from the editor.
const editorSpec = editorValidateSpecObject(parsed)
if (JSON.stringify(spec) !== JSON.stringify(editorSpec)) {
  console.error(
    '[sync:island] the ported validator and the editor validator disagree on this save — ' +
      're-sync the ported islandSpecCore modules with island-editor/src before landing this spec.',
  )
  process.exit(1)
}

// ── 2. Write the committed spec + frozen fallback ────────────────────────────

const normalized = `${serializeSpec(spec)}\n`
writeFileSync(specJsonPath, normalized)

const fallbackModule = `// GENERATED by scripts/sync-island-spec.ts — do not edit by hand.
// Frozen known-good snapshot of the committed island spec: the loader's
// fail-safe when defaultIslandSpec.json is missing or invalid (R2). Kept as a
// serialized (unknown-shaped) constant and re-validated on use, exactly like
// the committed file.
export const FALLBACK_ISLAND_SPEC: unknown = ${JSON.stringify(JSON.parse(normalized), null, 2)}
`
writeFileSync(fallbackPath, fallbackModule)

// ── 3. Regenerate the golden parity fixture from the EDITOR implementation ───

const blurred = editorBlurTiers(spec.grid)
const half = spec.worldSize / 2
const STEPS = 48 // 49×49 lattice: covers cell centers, midpoints, and edges
const heights: { x: number; z: number; h: number }[] = []
for (let j = 0; j <= STEPS; j++) {
  const z = -half + (j * spec.worldSize) / STEPS
  for (let i = 0; i <= STEPS; i++) {
    const x = -half + (i * spec.worldSize) / STEPS
    heights.push({ x, z, h: editorEvaluateHeight(editorSpec, x, z, blurred) })
  }
}

const objects = spec.objects.map((o) => ({
  id: o.id,
  kind: o.kind,
  ...editorWorldPositionOfObject(editorSpec, o, blurred),
}))

const blades: unknown[] = editorGrassBlades(editorSpec)
const golden = {
  note: 'GENERATED by scripts/sync-island-spec.ts from the island-editor implementation. Do not edit.',
  worldSize: spec.worldSize,
  seaLevel: spec.seaLevel,
  tierHeights: spec.tierHeights,
  heights,
  objects,
  grass: {
    count: blades.length,
    first: blades.slice(0, 8),
  },
}
mkdirSync(dirname(goldenPath), { recursive: true })
writeFileSync(goldenPath, `${JSON.stringify(golden, null, 2)}\n`)

console.log(
  `[sync:island] synced ${spec.objects.length} objects, ` +
    `${heights.length} golden height samples, ${blades.length} grass blades.`,
)
